CREATE TABLE payments (
    id               uuid PRIMARY KEY,
    idempotency_key  varchar(100) NOT NULL,
    request_hash     varchar(64)  NOT NULL,
    payer_account_id uuid         NOT NULL,
    payee_account_id uuid         NOT NULL,
    amount_minor     bigint       NOT NULL CHECK (amount_minor > 0),
    currency         varchar(3)   NOT NULL,
    status           varchar(20)  NOT NULL,
    failure_reason   varchar(200),
    created_at       timestamptz  NOT NULL,
    updated_at       timestamptz  NOT NULL,
    version          bigint       NOT NULL DEFAULT 0,
    CONSTRAINT uq_payments_idempotency_key UNIQUE (idempotency_key)
);

CREATE INDEX idx_payments_status ON payments (status);

CREATE TABLE outbox_events (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id     uuid         NOT NULL UNIQUE,
    aggregate_id uuid         NOT NULL,
    event_type   varchar(50)  NOT NULL,
    topic        varchar(100) NOT NULL,
    event_key    varchar(100) NOT NULL,
    payload      text         NOT NULL,
    created_at   timestamptz  NOT NULL,
    published_at timestamptz
);

-- Partial index: the relay only ever scans unpublished rows.
CREATE INDEX idx_outbox_unpublished ON outbox_events (id) WHERE published_at IS NULL;
