CREATE TABLE accounts (
    id             uuid PRIMARY KEY,
    owner_name     varchar(200) NOT NULL,
    currency       varchar(3)   NOT NULL,
    balance_minor  bigint       NOT NULL,
    system_account boolean      NOT NULL DEFAULT false,
    created_at     timestamptz  NOT NULL,
    version        bigint       NOT NULL DEFAULT 0,
    -- Defence in depth: even a bug in the service cannot overdraw a customer account.
    CONSTRAINT chk_customer_not_overdrawn CHECK (system_account OR balance_minor >= 0)
);

CREATE TABLE journal_entries (
    id         uuid PRIMARY KEY,
    payment_id uuid UNIQUE,          -- a payment can be posted at most once
    kind       varchar(20) NOT NULL,
    created_at timestamptz NOT NULL
);

-- Append-only. Signed amounts: positive = credit, negative = debit.
CREATE TABLE postings (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_entry_id uuid        NOT NULL REFERENCES journal_entries (id),
    account_id       uuid        NOT NULL REFERENCES accounts (id),
    amount_minor     bigint      NOT NULL CHECK (amount_minor <> 0),
    currency         varchar(3)  NOT NULL,
    created_at       timestamptz NOT NULL
);

CREATE INDEX idx_postings_account ON postings (account_id, id DESC);
CREATE INDEX idx_postings_entry ON postings (journal_entry_id);

CREATE TABLE processed_events (
    event_id     uuid PRIMARY KEY,
    processed_at timestamptz NOT NULL
);

CREATE TABLE outbox_events (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id     uuid         NOT NULL UNIQUE,
    aggregate_id uuid         NOT NULL,
    event_type   varchar(50)  NOT NULL,
    topic        varchar(100) NOT NULL,
    event_key    varchar(100) NOT NULL,
    payload      text         NOT NULL,
    created_at   timestamptz  NOT NULL,
    published_at timestamptz
);

CREATE INDEX idx_outbox_unpublished ON outbox_events (id) WHERE published_at IS NULL;

-- USD treasury: the system account that funds opening balances.
-- Its id is UUID.nameUUIDFromBytes("treasury:USD"), matching Account.treasuryId("USD").
INSERT INTO accounts (id, owner_name, currency, balance_minor, system_account, created_at, version)
VALUES ('4f5540b5-25e9-3d49-83fe-cb338c1417cf', 'Treasury (USD)', 'USD', 0, true, now(), 0);
